### ISSUE TITLE
genon2db errors

### ISSUE THREAD

**Issue by PikaGirl55** [bread-in-a-can/Canned-Bread-s-VOCALOIDDBTOOL-Swiss-Army-Knife#1]
I've set everything up properly but when I try to Generate DB I get this error in the command line

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\reube\Downloads\VocaloidDBTool-Swiss-Army-Knife-1.1\cannedbread_genon2db_GUI.py", line 280, in generate_ust
    self.generate_labfile(path_otoini, path_table, out_dir, tempo, notename, uta_vcv_mode, pause_length)
  File "C:\Users\reube\Downloads\VocaloidDBTool-Swiss-Army-Knife-1.1\cannedbread_genon2db_GUI.py", line 210, in generate_labfile
    self.force_otoinifile_cutoff_negative(path_otoini, path_otoini)
  File "C:\Users\reube\Downloads\VocaloidDBTool-Swiss-Army-Knife-1.1\cannedbread_genon2db_GUI.py", line 119, in force_otoinifile_cutoff_negative
    otoini = up.otoini.load(path_otoini_in)
  File "C:\Users\reube\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\utaupy\otoini.py", line 31, in load
    params = params[:2] + [float(v) for v in params[2:]]
  File "C:\Users\reube\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\utaupy\otoini.py", line 31, in <listcomp>
    params = params[:2] + [float(v) for v in params[2:]]
ValueError: could not convert string to float: ''

**Comment by LuciozUndiezz** [comment]
This means that the cutoff is empty in your oto.ini. I will add a fix to automatically make cutoff negative so this error won't throw up! 
I will be marking this as closed
